name: cross_file_image
description: ImageProvider for XFile.
version: 0.0.2
homepage: https://github.com/qiuxiang/cross_file_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
